social_networks:
  - type: truthsocial
    socialNetworkId: realDonaldTrump
    prompt: >-
      ä½ ç°åœ¨æ˜¯ä¸€åè´¢ç»ä¸“å®¶ï¼Œè¯·å¯¹ä»¥ä¸‹ç¾å›½æ€»ç»Ÿçš„å‘è¨€è¿›è¡Œåˆ†æï¼Œå¹¶ç»™æŒ‰æˆ‘æŒ‡å®šçš„æ ¼å¼è¿”å›åˆ†æç»“æœã€‚

      è¿™æ˜¯ä½ éœ€è¦åˆ†æçš„å†…å®¹ï¼š$content

      å¦‚æœéœ€è¦åˆ†æçš„å†…å®¹ä¸è´¢ç»ã€ç¾è‚¡ã€ä¸­ç¾å…³ç³»ã€ç¾å€ºå¸‚åœºã€ç§‘æŠ€è‚¡æˆ–åŠå¯¼ä½“è‚¡æœ‰å…³ï¼Œå°±æŒ‰ä¸‹é¢çš„æ ¼å¼è¾“å‡ºå†…å®¹ã€‚

      ## Brief Analysis

      åˆ†æç»“æœã€‚è¿™éƒ¨åˆ†ä¼šå±•ç¤ºä¸€ä¸ªåˆ—è¡¨ï¼Œåˆ—è¡¨ä¸­åˆ†åˆ«åŒ…å«ç¾è‚¡å¸‚åœºã€ç¾å€ºå¸‚åœºã€ç§‘æŠ€è‚¡ã€åŠå¯¼ä½“è‚¡ã€ä¸­å›½è‚¡ç¥¨å¸‚åœºã€é¦™æ¸¯è‚¡ç¥¨å¸‚åœºã€äººæ°‘å¸å…‘ç¾å…ƒæ±‡ç‡ã€ä¸­ç¾å…³ç³»è¿™8ä¸ªé€‰é¡¹ã€‚
      æ¯ä¸ªé€‰é¡¹çš„å€¼ä¸ºåˆ†åˆ«ä¸ºğŸ“ˆåˆ©å¤šå’ŒğŸ“‰åˆ©ç©ºã€‚å¦‚æœåˆ†æå†…å®¹å¯¹äºè¯¥é€‰é¡¹æ²¡æœ‰å½±å“ï¼Œå°±ä¸è¦é’ˆå¯¹è¿™ä¸ªé€‰é¡¹è¿”å›ä»»ä½•å†…å®¹ã€‚

      ## Summarize

      è¿™éƒ¨åˆ†éœ€è¦ç”¨éå¸¸ç®€æ˜æ‰¼è¦çš„æ–‡å­—å¯¹åˆ†æç»“æœè¿›è¡Œæ€»ç»“ï¼Œä»¥åŠè§£é‡Šä¸ºä»€ä¹ˆåœ¨ä¸Šé¢é’ˆå¯¹ä¸åŒé€‰é¡¹ä¼šå¾—å‡ºä¸åŒçš„ç»“è®ºã€‚
    messengers:
      - url: $WECOM_TRUMP_ROBOT_URL
        method: POST
        headers:
          Content-Type: application/json
        body:
          msgtype: markdown
          markdown:
            content: >-
              # [$poster_name]($poster_url) $post_time
              
              > $content
              
              $translation:zh-cn
              
              $ai_result
              
              Origin: [$post_url]($post_url)
      - url: $PRIVATE_BARK_URL
        method: POST
        headers:
          Content-Type: application/json; charset=utf-8
        body:
          title: "$poster_name: $translation:zh-cn"
          group: finance
          url: $post_url
          body: >-
            $content
            
            $ai_result
  - type: twitter
    socialNetworkId:
      - myfxtrader
      - HAOHONG_CFA
      - DeItaone
    prompt: >-
      ä½ ç°åœ¨æ˜¯ä¸€åè´¢ç»ä¸“å®¶ï¼Œè¯·å¯¹ä»¥ä¸‹è´¢ç»åšä¸»çš„å‘è¨€è¿›è¡Œåˆ†æï¼Œå¦‚æœéœ€è¦åˆ†æçš„å†…å®¹ä¸è´¢ç»ã€ç¾è‚¡ã€ä¸­ç¾å…³ç³»ã€ç¾å€ºå¸‚åœºã€ç§‘æŠ€è‚¡æˆ–åŠå¯¼ä½“è‚¡æœ‰å…³ï¼Œå°±ç”¨éå¸¸ç®€æ˜æ‰¼è¦çš„æ–‡å­—å¯¹åˆ†æç»“æœè¿›è¡Œæ€»ç»“ï¼Œä»¥åŠè§£é‡Šä¸€ä¸‹åŸå› ã€‚

      è¿™æ˜¯ä½ éœ€è¦åˆ†æçš„å†…å®¹ï¼š$content
    messengers:
      - url: $PRIVATE_BARK_URL
        method: POST
        headers:
          Content-Type: application/json; charset=utf-8
        body:
          title: "$poster_name: $translation:zh-cn"
          group: finance
          url: $post_url
          body: >-
            $content
            
            $ai_result
